### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by Flouse** [cryptape/ckb-node-probe-frontend#20]
![image](https://github.com/cryptape/ckb-node-probe-frontend/assets/1297478/6927adee-858d-43ee-8bbb-de0b635fb1f5)

## browser console
```js
cdnjs.cloudflare.com/ajax/libs/leaflet.heat/0.2.0/leaflet-heat.js:1     Failed to load resource: net::ERR_CONNECTION_RESET
main-b9b44be83d077b3a.js:9 TypeError: Cannot read properties of undefined (reading 'map')
    at index-19f4b096207faebb.js:1:7315
    at index-19f4b096207faebb.js:1:8098
    at lg (main-b9b44be83d077b3a.js:9:68388)
    at lA (main-b9b44be83d077b3a.js:9:79900)
    at lF (main-b9b44be83d077b3a.js:9:80538)
    at lD (main-b9b44be83d077b3a.js:9:80422)
    at lF (main-b9b44be83d077b3a.js:9:80518)
    at lD (main-b9b44be83d077b3a.js:9:80422)
    at lF (main-b9b44be83d077b3a.js:9:81483)
    at lD (main-b9b44be83d077b3a.js:9:80422)
an @ main-b9b44be83d077b3a.js:9
main-b9b44be83d077b3a.js:1 TypeError: Cannot read properties of undefined (reading 'map')
    at index-19f4b096207faebb.js:1:7315
    at index-19f4b096207faebb.js:1:8098
    at lg (main-b9b44be83d077b3a.js:9:68388)
    at lA (main-b9b44be83d077b3a.js:9:79900)
    at lF (main-b9b44be83d077b3a.js:9:80538)
    at lD (main-b9b44be83d077b3a.js:9:80422)
    at lF (main-b9b44be83d077b3a.js:9:80518)
    at lD (main-b9b44be83d077b3a.js:9:80422)
    at lF (main-b9b44be83d077b3a.js:9:81483)
    at lD (main-b9b44be83d077b3a.js:9:80422)
X @ main-b9b44be83d077b3a.js:1
main-b9b44be83d077b3a.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
X @ main-b9b44be83d077b3a.js:1
unpkg.com/leaflet.fullscreen@2.4.0/Control.FullScreen.js:1     Failed to load resource: net::ERR_CONNECTION_RESET
```

**Comment by Flouse** [comment]
It was just a network connection issue.
